server:
  port: 9000

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: api-gateway
    
#暴露全部监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    order-service: /apigateway/order/**
    product-service: /apigateway/product/**
    user-service: /apigateway/user/**
  ignored-patterns: /*-service/**
  sensitive-headers:
#  ignored-services: product-service
